import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: HomePage()));
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

final Map<String, Object> json = <String, Object>{
  "status": "ok",
  "status_message": "Query was successful",
  "data": {
    "movie_count": 57888,
    "limit": 20,
    "page_number": 1,
    "movies": [
      {
        "id": 58794,
        "url": "https://yts.mx/movies/the-apprenticeship-of-duddy-kravitz-1974",
        "imdb_code": "tt0071155",
        "title": "The Apprenticeship of Duddy Kravitz",
        "title_english": "The Apprenticeship of Duddy Kravitz",
        "title_long": "The Apprenticeship of Duddy Kravitz (1974)",
        "slug": "the-apprenticeship-of-duddy-kravitz-1974",
        "year": 1974,
        "rating": 6.8,
        "runtime": 120,
        "genres": ["Comedy", "Drama"],
        "summary":
            "The younger son of a working-class Jewish family in Montreal, Duddy Kravitz yearns to make a name for himself in society. This film chronicles his short and dubious rise to power, as well as his changing relationships with family and friends. Along the way the film explores the themes of anti-semitism and the responsibilities which come with adulthood.—Isabel Piedmont",
        "description_full":
            "The younger son of a working-class Jewish family in Montreal, Duddy Kravitz yearns to make a name for himself in society. This film chronicles his short and dubious rise to power, as well as his changing relationships with family and friends. Along the way the film explores the themes of anti-semitism and the responsibilities which come with adulthood.—Isabel Piedmont",
        "synopsis":
            "The younger son of a working-class Jewish family in Montreal, Duddy Kravitz yearns to make a name for himself in society. This film chronicles his short and dubious rise to power, as well as his changing relationships with family and friends. Along the way the film explores the themes of anti-semitism and the responsibilities which come with adulthood.—Isabel Piedmont",
        "yt_trailer_code": "Z6EQgI3P7kg",
        "language": "en",
        "mpa_rating": "",
        "background_image":
            "https://yts.mx/assets/images/movies/the_apprenticeship_of_duddy_kravitz_1974/background.jpg",
        "background_image_original":
            "https://yts.mx/assets/images/movies/the_apprenticeship_of_duddy_kravitz_1974/background.jpg",
        "small_cover_image":
            "https://yts.mx/assets/images/movies/the_apprenticeship_of_duddy_kravitz_1974/small-cover.jpg",
        "medium_cover_image":
            "https://yts.mx/assets/images/movies/the_apprenticeship_of_duddy_kravitz_1974/medium-cover.jpg",
        "large_cover_image":
            "https://yts.mx/assets/images/movies/the_apprenticeship_of_duddy_kravitz_1974/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/3FD38247708BA2E9453E2CC7ED6104544391D108",
            "hash": "3FD38247708BA2E9453E2CC7ED6104544391D108",
            "quality": "720p",
            "type": "bluray",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "1.09 GB",
            "size_bytes": 1170378588,
            "date_uploaded": "2023-12-28 07:36:25",
            "date_uploaded_unix": 1703745385
          },
          {
            "url": "https://yts.mx/torrent/download/9B0D448EB328EE70190D906DD5AD9E137C910859",
            "hash": "9B0D448EB328EE70190D906DD5AD9E137C910859",
            "quality": "1080p",
            "type": "bluray",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "2.02 GB",
            "size_bytes": 2168958484,
            "date_uploaded": "2023-12-28 09:11:18",
            "date_uploaded_unix": 1703751078
          }
        ],
        "date_uploaded": "2023-12-28 07:36:25",
        "date_uploaded_unix": 1703745385
      },
      {
        "id": 58793,
        "url": "https://yts.mx/movies/santa-maybe-2023",
        "imdb_code": "tt29931745",
        "title": "Santa, Maybe",
        "title_english": "Santa, Maybe",
        "title_long": "Santa, Maybe (2023)",
        "slug": "santa-maybe-2023",
        "year": 2023,
        "rating": 6.4,
        "runtime": 0,
        "genres": ["Drama", "Romance"],
        "summary": "",
        "description_full": "",
        "synopsis": "",
        "yt_trailer_code": "",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/santa_maybe_2023/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/santa_maybe_2023/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/santa_maybe_2023/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/santa_maybe_2023/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/santa_maybe_2023/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/DFC998D2871FC31742D536ADC4799F0BB8C9CBFE",
            "hash": "DFC998D2871FC31742D536ADC4799F0BB8C9CBFE",
            "quality": "720p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "786.25 MB",
            "size_bytes": 824442880,
            "date_uploaded": "2023-12-28 05:20:18",
            "date_uploaded_unix": 1703737218
          },
          {
            "url": "https://yts.mx/torrent/download/9F6ED776B71C80AF0867D1BDA6E3BD90A8BD3A5B",
            "hash": "9F6ED776B71C80AF0867D1BDA6E3BD90A8BD3A5B",
            "quality": "1080p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "1.42 GB",
            "size_bytes": 1524713390,
            "date_uploaded": "2023-12-28 06:21:59",
            "date_uploaded_unix": 1703740919
          }
        ],
        "date_uploaded": "2023-12-28 05:20:18",
        "date_uploaded_unix": 1703737218
      },
      {
        "id": 58792,
        "url": "https://yts.mx/movies/a-royal-christmas-holiday-2023",
        "imdb_code": "tt28546386",
        "title": "A Royal Christmas Holiday",
        "title_english": "A Royal Christmas Holiday",
        "title_long": "A Royal Christmas Holiday (2023)",
        "slug": "a-royal-christmas-holiday-2023",
        "year": 2023,
        "rating": 7,
        "runtime": 0,
        "genres": ["Romance"],
        "summary": "",
        "description_full": "",
        "synopsis": "",
        "yt_trailer_code": "",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/a_royal_christmas_holiday_2023/background.jpg",
        "background_image_original":
            "https://yts.mx/assets/images/movies/a_royal_christmas_holiday_2023/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/a_royal_christmas_holiday_2023/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/a_royal_christmas_holiday_2023/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/a_royal_christmas_holiday_2023/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/719DF57975318268B8CD6C4AAEF71CB92754E1EB",
            "hash": "719DF57975318268B8CD6C4AAEF71CB92754E1EB",
            "quality": "720p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "798.85 MB",
            "size_bytes": 837654938,
            "date_uploaded": "2023-12-28 05:28:17",
            "date_uploaded_unix": 1703737697
          },
          {
            "url": "https://yts.mx/torrent/download/AE4631EAAE34B70CC9C54C8067AA790296A3203E",
            "hash": "AE4631EAAE34B70CC9C54C8067AA790296A3203E",
            "quality": "1080p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "1.45 GB",
            "size_bytes": 1556925645,
            "date_uploaded": "2023-12-28 06:42:20",
            "date_uploaded_unix": 1703742140
          }
        ],
        "date_uploaded": "2023-12-28 05:28:17",
        "date_uploaded_unix": 1703737697
      },
      {
        "id": 58791,
        "url": "https://yts.mx/movies/my-christmas-hero-2023",
        "imdb_code": "tt27542956",
        "title": "My Christmas Hero",
        "title_english": "My Christmas Hero",
        "title_long": "My Christmas Hero (2023)",
        "slug": "my-christmas-hero-2023",
        "year": 2023,
        "rating": 6.8,
        "runtime": 84,
        "genres": ["Drama", "Family", "Romance"],
        "summary": "",
        "description_full": "",
        "synopsis": "",
        "yt_trailer_code": "2iCXEZm4CLs",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/my_christmas_hero_2023/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/my_christmas_hero_2023/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/my_christmas_hero_2023/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/my_christmas_hero_2023/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/my_christmas_hero_2023/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/38BC922983A354C2FFE8F19D5A1220D083458206",
            "hash": "38BC922983A354C2FFE8F19D5A1220D083458206",
            "quality": "720p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "776.5 MB",
            "size_bytes": 814219264,
            "date_uploaded": "2023-12-28 00:43:33",
            "date_uploaded_unix": 1703720613
          },
          {
            "url": "https://yts.mx/torrent/download/82447F4B1E7C8292EB0B4B34971D127342345D76",
            "hash": "82447F4B1E7C8292EB0B4B34971D127342345D76",
            "quality": "1080p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "1.4 GB",
            "size_bytes": 1503238554,
            "date_uploaded": "2023-12-28 01:51:21",
            "date_uploaded_unix": 1703724681
          }
        ],
        "date_uploaded": "2023-12-28 00:43:33",
        "date_uploaded_unix": 1703720613
      },
      {
        "id": 58790,
        "url": "https://yts.mx/movies/traveling-light-2021",
        "imdb_code": "tt15439652",
        "title": "Traveling Light",
        "title_english": "Traveling Light",
        "title_long": "Traveling Light (2021)",
        "slug": "traveling-light-2021",
        "year": 2021,
        "rating": 5.8,
        "runtime": 90,
        "genres": ["Drama"],
        "summary": "",
        "description_full": "",
        "synopsis": "",
        "yt_trailer_code": "",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/traveling_light_2021/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/traveling_light_2021/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/traveling_light_2021/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/traveling_light_2021/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/traveling_light_2021/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/641C1838EC6C42030EFD5128A58FD9F514235B2D",
            "hash": "641C1838EC6C42030EFD5128A58FD9F514235B2D",
            "quality": "720p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "832.3 MB",
            "size_bytes": 872729805,
            "date_uploaded": "2023-12-27 21:04:27",
            "date_uploaded_unix": 1703707467
          },
          {
            "url": "https://yts.mx/torrent/download/DA770F5147FAB1B18C735D2843094259602EC5BB",
            "hash": "DA770F5147FAB1B18C735D2843094259602EC5BB",
            "quality": "1080p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "5.1",
            "seeds": 0,
            "peers": 0,
            "size": "1.67 GB",
            "size_bytes": 1793148846,
            "date_uploaded": "2023-12-27 21:58:43",
            "date_uploaded_unix": 1703710723
          }
        ],
        "date_uploaded": "2023-12-27 21:04:27",
        "date_uploaded_unix": 1703707467
      },
      {
        "id": 58789,
        "url": "https://yts.mx/movies/creepypasta-2023",
        "imdb_code": "tt12971854",
        "title": "Creepypasta",
        "title_english": "Creepypasta",
        "title_long": "Creepypasta (2023)",
        "slug": "creepypasta-2023",
        "year": 2023,
        "rating": 3.5,
        "runtime": 0,
        "genres": ["Horror"],
        "summary": "",
        "description_full": "",
        "synopsis": "",
        "yt_trailer_code": "m_m4W0J1gDA",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/creepypasta_2023/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/creepypasta_2023/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/creepypasta_2023/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/creepypasta_2023/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/creepypasta_2023/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/42190CEAE39AC0BBD4F710049398B97151E72BA9",
            "hash": "42190CEAE39AC0BBD4F710049398B97151E72BA9",
            "quality": "720p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 100,
            "peers": 37,
            "size": "778.26 MB",
            "size_bytes": 816064758,
            "date_uploaded": "2023-12-27 19:34:07",
            "date_uploaded_unix": 1703702047
          },
          {
            "url": "https://yts.mx/torrent/download/ED6AC9B2C3D822552A6EC2D27C4EAF3C040A6820",
            "hash": "ED6AC9B2C3D822552A6EC2D27C4EAF3C040A6820",
            "quality": "1080p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "1.41 GB",
            "size_bytes": 1513975972,
            "date_uploaded": "2023-12-27 20:32:52",
            "date_uploaded_unix": 1703705572
          }
        ],
        "date_uploaded": "2023-12-27 19:34:07",
        "date_uploaded_unix": 1703702047
      },
      {
        "id": 58788,
        "url": "https://yts.mx/movies/a-cowboy-christmas-romance-2023",
        "imdb_code": "tt29521467",
        "title": "A Cowboy Christmas Romance",
        "title_english": "A Cowboy Christmas Romance",
        "title_long": "A Cowboy Christmas Romance (2023)",
        "slug": "a-cowboy-christmas-romance-2023",
        "year": 2023,
        "rating": 6.7,
        "runtime": 85,
        "genres": ["Romance"],
        "summary": "",
        "description_full": "",
        "synopsis": "",
        "yt_trailer_code": "",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/a_cowboy_christmas_romance_2023/background.jpg",
        "background_image_original":
            "https://yts.mx/assets/images/movies/a_cowboy_christmas_romance_2023/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/a_cowboy_christmas_romance_2023/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/a_cowboy_christmas_romance_2023/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/a_cowboy_christmas_romance_2023/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/7DC0F71BA11FA82FC2043095B2030FD6FB37B977",
            "hash": "7DC0F71BA11FA82FC2043095B2030FD6FB37B977",
            "quality": "720p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 100,
            "peers": 47,
            "size": "782.23 MB",
            "size_bytes": 820227604,
            "date_uploaded": "2023-12-27 17:54:55",
            "date_uploaded_unix": 1703696095
          },
          {
            "url": "https://yts.mx/torrent/download/5396BA831A51904931C812926051724A5F3DFFE6",
            "hash": "5396BA831A51904931C812926051724A5F3DFFE6",
            "quality": "1080p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 100,
            "peers": 39,
            "size": "1.42 GB",
            "size_bytes": 1524713390,
            "date_uploaded": "2023-12-27 18:57:38",
            "date_uploaded_unix": 1703699858
          }
        ],
        "date_uploaded": "2023-12-27 17:54:55",
        "date_uploaded_unix": 1703696095
      },
      {
        "id": 58787,
        "url": "https://yts.mx/movies/laughing-all-the-way-2023",
        "imdb_code": "tt30241039",
        "title": "Laughing All the Way",
        "title_english": "Laughing All the Way",
        "title_long": "Laughing All the Way (2023)",
        "slug": "laughing-all-the-way-2023",
        "year": 2023,
        "rating": 5.9,
        "runtime": 87,
        "genres": ["Comedy", "Romance"],
        "summary": "",
        "description_full": "",
        "synopsis": "",
        "yt_trailer_code": "",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/laughing_all_the_way_2023/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/laughing_all_the_way_2023/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/laughing_all_the_way_2023/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/laughing_all_the_way_2023/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/laughing_all_the_way_2023/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/F3060D4691BE954675FF82816E4C4E5560AED008",
            "hash": "F3060D4691BE954675FF82816E4C4E5560AED008",
            "quality": "720p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "805.09 MB",
            "size_bytes": 844198052,
            "date_uploaded": "2023-12-27 17:47:35",
            "date_uploaded_unix": 1703695655
          },
          {
            "url": "https://yts.mx/torrent/download/9E153BB82CCDEB3CAFAB2077DD9D15DD5F2E030B",
            "hash": "9E153BB82CCDEB3CAFAB2077DD9D15DD5F2E030B",
            "quality": "1080p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "1.46 GB",
            "size_bytes": 1567663063,
            "date_uploaded": "2023-12-27 18:47:19",
            "date_uploaded_unix": 1703699239
          }
        ],
        "date_uploaded": "2023-12-27 17:47:35",
        "date_uploaded_unix": 1703695655
      },
      {
        "id": 58786,
        "url": "https://yts.mx/movies/the-genesis-code-2010",
        "imdb_code": "tt1481576",
        "title": "The Genesis Code",
        "title_english": "The Genesis Code",
        "title_long": "The Genesis Code (2010)",
        "slug": "the-genesis-code-2010",
        "year": 2010,
        "rating": 4.9,
        "runtime": 138,
        "genres": ["Drama"],
        "summary": "",
        "description_full": "",
        "synopsis": "",
        "yt_trailer_code": "2p4Cs_QkwsM",
        "language": "en",
        "mpa_rating": "PG",
        "background_image": "https://yts.mx/assets/images/movies/the_genesis_code_2010/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/the_genesis_code_2010/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/the_genesis_code_2010/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/the_genesis_code_2010/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/the_genesis_code_2010/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/6CE37DAAE2474D62B5F492D1D12F4C56B763BF25",
            "hash": "6CE37DAAE2474D62B5F492D1D12F4C56B763BF25",
            "quality": "720p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "1.24 GB",
            "size_bytes": 1331439862,
            "date_uploaded": "2023-12-27 15:53:48",
            "date_uploaded_unix": 1703688828
          },
          {
            "url": "https://yts.mx/torrent/download/67DC6769C6A3B3B7FB153980CDEECF9EE3FC44DC",
            "hash": "67DC6769C6A3B3B7FB153980CDEECF9EE3FC44DC",
            "quality": "1080p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "5.1",
            "seeds": 96,
            "peers": 25,
            "size": "2.54 GB",
            "size_bytes": 2727304233,
            "date_uploaded": "2023-12-27 17:20:44",
            "date_uploaded_unix": 1703694044
          }
        ],
        "date_uploaded": "2023-12-27 15:53:48",
        "date_uploaded_unix": 1703688828
      },
      {
        "id": 58785,
        "url": "https://yts.mx/movies/hell-camp-teen-nightmare-2023",
        "imdb_code": "tt30225680",
        "title": "Hell Camp: Teen Nightmare",
        "title_english": "Hell Camp: Teen Nightmare",
        "title_long": "Hell Camp: Teen Nightmare (2023)",
        "slug": "hell-camp-teen-nightmare-2023",
        "year": 2023,
        "rating": 6.5,
        "runtime": 90,
        "genres": ["Documentary"],
        "summary": "",
        "description_full": "",
        "synopsis": "",
        "yt_trailer_code": "f6GuNxVvapM",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/hell_camp_teen_nightmare_2023/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/hell_camp_teen_nightmare_2023/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/hell_camp_teen_nightmare_2023/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/hell_camp_teen_nightmare_2023/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/hell_camp_teen_nightmare_2023/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/09DE1CAFB5730506FAB6867E240297972BF01382",
            "hash": "09DE1CAFB5730506FAB6867E240297972BF01382",
            "quality": "720p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 99,
            "peers": 39,
            "size": "832.82 MB",
            "size_bytes": 873275064,
            "date_uploaded": "2023-12-27 10:20:36",
            "date_uploaded_unix": 1703668836
          },
          {
            "url": "https://yts.mx/torrent/download/E83C78091D56EFC771F4672C7358E454B473B709",
            "hash": "E83C78091D56EFC771F4672C7358E454B473B709",
            "quality": "1080p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "5.1",
            "seeds": 0,
            "peers": 0,
            "size": "1.67 GB",
            "size_bytes": 1793148846,
            "date_uploaded": "2023-12-27 11:13:22",
            "date_uploaded_unix": 1703672002
          }
        ],
        "date_uploaded": "2023-12-27 10:20:36",
        "date_uploaded_unix": 1703668836
      },
      {
        "id": 58784,
        "url": "https://yts.mx/movies/a-very-good-girl-2023",
        "imdb_code": "tt27327494",
        "title": "A Very Good Girl",
        "title_english": "A Very Good Girl",
        "title_long": "A Very Good Girl (2023)",
        "slug": "a-very-good-girl-2023",
        "year": 2023,
        "rating": 6.1,
        "runtime": 117,
        "genres": ["Comedy", "Drama", "Mystery", "Thriller"],
        "summary": "",
        "description_full": "",
        "synopsis": "",
        "yt_trailer_code": "jFfzQYNY0AE",
        "language": "tl",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/a_very_good_girl_2023/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/a_very_good_girl_2023/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/a_very_good_girl_2023/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/a_very_good_girl_2023/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/a_very_good_girl_2023/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/4052AF2968A1CAAA01E8CF73A5ACBF0F5CDCA9CC",
            "hash": "4052AF2968A1CAAA01E8CF73A5ACBF0F5CDCA9CC",
            "quality": "720p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 100,
            "peers": 82,
            "size": "1.06 GB",
            "size_bytes": 1138166333,
            "date_uploaded": "2023-12-27 08:25:23",
            "date_uploaded_unix": 1703661923
          },
          {
            "url": "https://yts.mx/torrent/download/88F1127770B6AD76ED7AF0FA26A78E37082D982D",
            "hash": "88F1127770B6AD76ED7AF0FA26A78E37082D982D",
            "quality": "1080p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "5.1",
            "seeds": 0,
            "peers": 0,
            "size": "2.18 GB",
            "size_bytes": 2340757176,
            "date_uploaded": "2023-12-27 09:49:47",
            "date_uploaded_unix": 1703666987
          }
        ],
        "date_uploaded": "2023-12-27 08:25:23",
        "date_uploaded_unix": 1703661923
      },
      {
        "id": 58783,
        "url": "https://yts.mx/movies/appointment-with-a-shadow-1957",
        "imdb_code": "tt0051370",
        "title": "Appointment with a Shadow",
        "title_english": "Appointment with a Shadow",
        "title_long": "Appointment with a Shadow (1957)",
        "slug": "appointment-with-a-shadow-1957",
        "year": 1957,
        "rating": 6.5,
        "runtime": 72,
        "genres": ["Crime", "Drama", "Film-Noir"],
        "summary": "",
        "description_full": "",
        "synopsis": "",
        "yt_trailer_code": "",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/appointment_with_a_shadow_1957/background.jpg",
        "background_image_original":
            "https://yts.mx/assets/images/movies/appointment_with_a_shadow_1957/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/appointment_with_a_shadow_1957/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/appointment_with_a_shadow_1957/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/appointment_with_a_shadow_1957/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/5C90954F70A4C5A73F873EBFE971C4A85685B4AF",
            "hash": "5C90954F70A4C5A73F873EBFE971C4A85685B4AF",
            "quality": "720p",
            "type": "bluray",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 46,
            "peers": 14,
            "size": "666.44 MB",
            "size_bytes": 698812989,
            "date_uploaded": "2023-12-27 05:01:27",
            "date_uploaded_unix": 1703649687
          },
          {
            "url": "https://yts.mx/torrent/download/1B70FDFCFD1945441496C0ECF8414A44A88D3636",
            "hash": "1B70FDFCFD1945441496C0ECF8414A44A88D3636",
            "quality": "1080p",
            "type": "bluray",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 100,
            "peers": 34,
            "size": "1.21 GB",
            "size_bytes": 1299227607,
            "date_uploaded": "2023-12-27 05:49:55",
            "date_uploaded_unix": 1703652595
          }
        ],
        "date_uploaded": "2023-12-27 05:01:27",
        "date_uploaded_unix": 1703649687
      },
      {
        "id": 58782,
        "url": "https://yts.mx/movies/dracula-reborn-2012",
        "imdb_code": "tt2320030",
        "title": "Dracula: Reborn",
        "title_english": "Dracula: Reborn",
        "title_long": "Dracula: Reborn (2012)",
        "slug": "dracula-reborn-2012",
        "year": 2012,
        "rating": 3.2,
        "runtime": 88,
        "genres": ["Drama", "Horror"],
        "summary": "",
        "description_full": "",
        "synopsis": "",
        "yt_trailer_code": "",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/dracula_reborn_2012/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/dracula_reborn_2012/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/dracula_reborn_2012/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/dracula_reborn_2012/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/dracula_reborn_2012/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/DD167947BA605F8BFADFB1F582439F1AE4027816",
            "hash": "DD167947BA605F8BFADFB1F582439F1AE4027816",
            "quality": "720p",
            "type": "bluray",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "821.67 MB",
            "size_bytes": 861583442,
            "date_uploaded": "2023-12-27 03:40:51",
            "date_uploaded_unix": 1703644851
          },
          {
            "url": "https://yts.mx/torrent/download/31A64F6C83B11FD60F28B3E6AAD618F7AFAC3626",
            "hash": "31A64F6C83B11FD60F28B3E6AAD618F7AFAC3626",
            "quality": "1080p",
            "type": "bluray",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "5.1",
            "seeds": 61,
            "peers": 28,
            "size": "1.65 GB",
            "size_bytes": 1771674010,
            "date_uploaded": "2023-12-27 04:33:57",
            "date_uploaded_unix": 1703648037
          }
        ],
        "date_uploaded": "2023-12-27 03:40:51",
        "date_uploaded_unix": 1703644851
      },
      {
        "id": 58781,
        "url": "https://yts.mx/movies/namme-2017",
        "imdb_code": "tt7565614",
        "title": "Namme",
        "title_english": "Namme",
        "title_long": "Namme (2017)",
        "slug": "namme-2017",
        "year": 2017,
        "rating": 7.4,
        "runtime": 91,
        "genres": ["Drama"],
        "summary": "",
        "description_full": "",
        "synopsis": "",
        "yt_trailer_code": "alWJZkfJZFI",
        "language": "ka",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/namme_2017/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/namme_2017/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/namme_2017/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/namme_2017/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/namme_2017/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/B9FF1C0BF5F7BCE8C14F95B0103915C352D93610",
            "hash": "B9FF1C0BF5F7BCE8C14F95B0103915C352D93610",
            "quality": "720p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "833.29 MB",
            "size_bytes": 873767895,
            "date_uploaded": "2023-12-27 06:43:59",
            "date_uploaded_unix": 1703655839
          },
          {
            "url": "https://yts.mx/torrent/download/18F0B0B3134C2AA6582BB7F172CDF86814B7D8C2",
            "hash": "18F0B0B3134C2AA6582BB7F172CDF86814B7D8C2",
            "quality": "1080p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 43,
            "peers": 20,
            "size": "1.51 GB",
            "size_bytes": 1621350154,
            "date_uploaded": "2023-12-27 07:28:48",
            "date_uploaded_unix": 1703658528
          }
        ],
        "date_uploaded": "2023-12-27 06:43:59",
        "date_uploaded_unix": 1703655839
      },
      {
        "id": 58779,
        "url": "https://yts.mx/movies/the-scapegoat-2012",
        "imdb_code": "tt2084977",
        "title": "The Scapegoat",
        "title_english": "The Scapegoat",
        "title_long": "The Scapegoat (2012)",
        "slug": "the-scapegoat-2012",
        "year": 2012,
        "rating": 7.2,
        "runtime": 108,
        "genres": ["Drama"],
        "summary":
            "As England is preparing for the coronation of Elizabeth II, schoolmaster John Standing (Matthew Rhys) comes face to face with Johnny Spence (Matthew Rhys), his exact double in appearance. After a night of drinking, Standing awakes to find Spence has stolen his identity. Unsuccessful at explaining the unusual situation, Standing settles into the vacancy left by Johnny Spence. Yet with his new life comes numerous problems, including trying to juggle a wife and two mistresses and family secrets that could prove to be deadly.—L. Hamre",
        "description_full":
            "As England is preparing for the coronation of Elizabeth II, schoolmaster John Standing (Matthew Rhys) comes face to face with Johnny Spence (Matthew Rhys), his exact double in appearance. After a night of drinking, Standing awakes to find Spence has stolen his identity. Unsuccessful at explaining the unusual situation, Standing settles into the vacancy left by Johnny Spence. Yet with his new life comes numerous problems, including trying to juggle a wife and two mistresses and family secrets that could prove to be deadly.—L. Hamre",
        "synopsis":
            "As England is preparing for the coronation of Elizabeth II, schoolmaster John Standing (Matthew Rhys) comes face to face with Johnny Spence (Matthew Rhys), his exact double in appearance. After a night of drinking, Standing awakes to find Spence has stolen his identity. Unsuccessful at explaining the unusual situation, Standing settles into the vacancy left by Johnny Spence. Yet with his new life comes numerous problems, including trying to juggle a wife and two mistresses and family secrets that could prove to be deadly.—L. Hamre",
        "yt_trailer_code": "8AbfgNNrmss",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/the_scapegoat_2012/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/the_scapegoat_2012/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/the_scapegoat_2012/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/the_scapegoat_2012/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/the_scapegoat_2012/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/7172B6C258580AB3DCEAD708024CEB69676D1048",
            "hash": "7172B6C258580AB3DCEAD708024CEB69676D1048",
            "quality": "720p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "989.58 MB",
            "size_bytes": 1037649838,
            "date_uploaded": "2023-12-28 04:35:34",
            "date_uploaded_unix": 1703734534
          },
          {
            "url": "https://yts.mx/torrent/download/65E16BD9C3CA79125BFC6C0FF3BFFC6DB5D6D2C2",
            "hash": "65E16BD9C3CA79125BFC6C0FF3BFFC6DB5D6D2C2",
            "quality": "1080p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "1.79 GB",
            "size_bytes": 1921997865,
            "date_uploaded": "2023-12-28 06:48:27",
            "date_uploaded_unix": 1703742507
          }
        ],
        "date_uploaded": "2023-12-28 04:35:34",
        "date_uploaded_unix": 1703734534
      },
      {
        "id": 58780,
        "url": "https://yts.mx/movies/vampyros-lesbos-1971",
        "imdb_code": "tt0066380",
        "title": "Vampyros Lesbos",
        "title_english": "Vampyros Lesbos",
        "title_long": "Vampyros Lesbos (1971)",
        "slug": "vampyros-lesbos-1971",
        "year": 1971,
        "rating": 5.4,
        "runtime": 89,
        "genres": ["Drama", "Horror"],
        "summary":
            "Linda is a young American lawyer, working in a law office in Istanbul. During the night, she has passionate dreams in which a sexy brunette harasses, and makes love to her, from which she's unable to defend herself. A minor case about an inheritance forces her to travel to one of the small islands off the Turkish coast. Then, her nightmares come upon her - in a lively manner.—Artemis-9",
        "description_full":
            "Linda is a young American lawyer, working in a law office in Istanbul. During the night, she has passionate dreams in which a sexy brunette harasses, and makes love to her, from which she's unable to defend herself. A minor case about an inheritance forces her to travel to one of the small islands off the Turkish coast. Then, her nightmares come upon her - in a lively manner.—Artemis-9",
        "synopsis":
            "Linda is a young American lawyer, working in a law office in Istanbul. During the night, she has passionate dreams in which a sexy brunette harasses, and makes love to her, from which she's unable to defend herself. A minor case about an inheritance forces her to travel to one of the small islands off the Turkish coast. Then, her nightmares come upon her - in a lively manner.—Artemis-9",
        "yt_trailer_code": "CXx_mnb4Yk8",
        "language": "es",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/vampyros_lesbos_1971/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/vampyros_lesbos_1971/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/vampyros_lesbos_1971/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/vampyros_lesbos_1971/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/vampyros_lesbos_1971/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/04FFDC2640CEBB924FBD126E3DA3E7C03023271E",
            "hash": "04FFDC2640CEBB924FBD126E3DA3E7C03023271E",
            "quality": "720p",
            "type": "bluray",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 100,
            "peers": 100,
            "size": "820.17 MB",
            "size_bytes": 860010578,
            "date_uploaded": "2023-12-27 02:44:43",
            "date_uploaded_unix": 1703641483
          }
        ],
        "date_uploaded": "2023-12-27 02:44:43",
        "date_uploaded_unix": 1703641483
      },
      {
        "id": 58775,
        "url": "https://yts.mx/movies/birds-of-america-2008",
        "imdb_code": "tt1029134",
        "title": "Birds of America",
        "title_english": "Birds of America",
        "title_long": "Birds of America (2008)",
        "slug": "birds-of-america-2008",
        "year": 2008,
        "rating": 6,
        "runtime": 85,
        "genres": ["Comedy", "Drama"],
        "summary":
            "When Morrie was a teenager, his parents died, leaving him a house, an irritable bowel, and siblings Jay and Ida to raise. Jump ahead 20 years: Jay is homeless, fits poorly into society, and was recently injured; Ida is jobless and sleeps with strangers; Morrie is married to the long-suffering Betty who is waiting for Morrie to get tenure before having children. They constantly have to kiss up to their holier-than-thou neighbors, one of whom is Morrie's department head. Morrie brings Jay home to recover, Ida decides to visit, the siblings make the neighbors ill at ease, a strange woman visits, and the cops want to talk to Jay. What about Morrie's irritated bowels?—",
        "description_full":
            "When Morrie was a teenager, his parents died, leaving him a house, an irritable bowel, and siblings Jay and Ida to raise. Jump ahead 20 years: Jay is homeless, fits poorly into society, and was recently injured; Ida is jobless and sleeps with strangers; Morrie is married to the long-suffering Betty who is waiting for Morrie to get tenure before having children. They constantly have to kiss up to their holier-than-thou neighbors, one of whom is Morrie's department head. Morrie brings Jay home to recover, Ida decides to visit, the siblings make the neighbors ill at ease, a strange woman visits, and the cops want to talk to Jay. What about Morrie's irritated bowels?—",
        "synopsis":
            "When Morrie was a teenager, his parents died, leaving him a house, an irritable bowel, and siblings Jay and Ida to raise. Jump ahead 20 years: Jay is homeless, fits poorly into society, and was recently injured; Ida is jobless and sleeps with strangers; Morrie is married to the long-suffering Betty who is waiting for Morrie to get tenure before having children. They constantly have to kiss up to their holier-than-thou neighbors, one of whom is Morrie's department head. Morrie brings Jay home to recover, Ida decides to visit, the siblings make the neighbors ill at ease, a strange woman visits, and the cops want to talk to Jay. What about Morrie's irritated bowels?—",
        "yt_trailer_code": "UsvbJ-c26fI",
        "language": "en",
        "mpa_rating": "R",
        "background_image": "https://yts.mx/assets/images/movies/birds_of_america_2008/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/birds_of_america_2008/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/birds_of_america_2008/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/birds_of_america_2008/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/birds_of_america_2008/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/179829E19B778460BFB6F94E24B018112A0D2D98",
            "hash": "179829E19B778460BFB6F94E24B018112A0D2D98",
            "quality": "720p",
            "type": "bluray",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 82,
            "peers": 39,
            "size": "778.33 MB",
            "size_bytes": 816138158,
            "date_uploaded": "2023-12-27 03:09:46",
            "date_uploaded_unix": 1703642986
          }
        ],
        "date_uploaded": "2023-12-27 03:09:46",
        "date_uploaded_unix": 1703642986
      },
      {
        "id": 58774,
        "url": "https://yts.mx/movies/hunger-2009",
        "imdb_code": "tt1176252",
        "title": "Hunger",
        "title_english": "Hunger",
        "title_long": "Hunger (2009)",
        "slug": "hunger-2009",
        "year": 2009,
        "rating": 5.2,
        "runtime": 101,
        "genres": ["Action", "Crime", "Horror", "Thriller"],
        "summary":
            "Hunger is a dark exploration into the breakdown of humanity. How far would you go to survive in the most extreme of circumstances? Five strangers awaken to find themselves trapped in an underground dungeon. They soon realize they are the subjects of one man's sadistic experiment to test the depths of a human being's will to survive. As the days go by with no means of escape, their hunger increases as their humanity fades away.—Anonymous",
        "description_full":
            "Hunger is a dark exploration into the breakdown of humanity. How far would you go to survive in the most extreme of circumstances? Five strangers awaken to find themselves trapped in an underground dungeon. They soon realize they are the subjects of one man's sadistic experiment to test the depths of a human being's will to survive. As the days go by with no means of escape, their hunger increases as their humanity fades away.—Anonymous",
        "synopsis":
            "Hunger is a dark exploration into the breakdown of humanity. How far would you go to survive in the most extreme of circumstances? Five strangers awaken to find themselves trapped in an underground dungeon. They soon realize they are the subjects of one man's sadistic experiment to test the depths of a human being's will to survive. As the days go by with no means of escape, their hunger increases as their humanity fades away.—Anonymous",
        "yt_trailer_code": "A0shVsHcU4c",
        "language": "en",
        "mpa_rating": "R",
        "background_image": "https://yts.mx/assets/images/movies/hunger_2009/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/hunger_2009/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/hunger_2009/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/hunger_2009/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/hunger_2009/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/FBED2C50D61F6A7F54E5EA83AD46E403EE755A59",
            "hash": "FBED2C50D61F6A7F54E5EA83AD46E403EE755A59",
            "quality": "720p",
            "type": "bluray",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "930.88 MB",
            "size_bytes": 976098427,
            "date_uploaded": "2023-12-27 12:34:43",
            "date_uploaded_unix": 1703676883
          },
          {
            "url": "https://yts.mx/torrent/download/9BC621526E81DF6D357F658FCB61735FF73C8577",
            "hash": "9BC621526E81DF6D357F658FCB61735FF73C8577",
            "quality": "1080p",
            "type": "bluray",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "5.1",
            "seeds": 0,
            "peers": 0,
            "size": "1.87 GB",
            "size_bytes": 2007897211,
            "date_uploaded": "2023-12-27 13:18:26",
            "date_uploaded_unix": 1703679506
          }
        ],
        "date_uploaded": "2023-12-27 12:34:43",
        "date_uploaded_unix": 1703676883
      },
      {
        "id": 58776,
        "url": "https://yts.mx/movies/shirkers-2018",
        "imdb_code": "tt7472352",
        "title": "Shirkers",
        "title_english": "Shirkers",
        "title_long": "Shirkers (2018)",
        "slug": "shirkers-2018",
        "year": 2018,
        "rating": 7.3,
        "runtime": 97,
        "genres": ["Documentary"],
        "summary":
            "In 1992, teenager Sandi Tan and her friends Sophie and Jasmine shot Singapore's first indie-a road movie called \"Shirkers\"-with their enigmatic American mentor, Georges Cardona. Sandi wrote the script and played the lead, a killer named S. After shooting wrapped, Georges vanished with all the footage! 20 years later, the 16mm cans are recovered in New Orleans, sending Sandi-now a novelist in Los Angeles-on a new personal odyssey across two continents and many media: 16mm, digital, Hi8, Super8, slides, animation and handwritten letters. A kaleidoscopic punk rock ghost story!",
        "description_full":
            "In 1992, teenager Sandi Tan and her friends Sophie and Jasmine shot Singapore's first indie-a road movie called \"Shirkers\"-with their enigmatic American mentor, Georges Cardona. Sandi wrote the script and played the lead, a killer named S. After shooting wrapped, Georges vanished with all the footage! 20 years later, the 16mm cans are recovered in New Orleans, sending Sandi-now a novelist in Los Angeles-on a new personal odyssey across two continents and many media: 16mm, digital, Hi8, Super8, slides, animation and handwritten letters. A kaleidoscopic punk rock ghost story!",
        "synopsis":
            "In 1992, teenager Sandi Tan and her friends Sophie and Jasmine shot Singapore's first indie-a road movie called \"Shirkers\"-with their enigmatic American mentor, Georges Cardona. Sandi wrote the script and played the lead, a killer named S. After shooting wrapped, Georges vanished with all the footage! 20 years later, the 16mm cans are recovered in New Orleans, sending Sandi-now a novelist in Los Angeles-on a new personal odyssey across two continents and many media: 16mm, digital, Hi8, Super8, slides, animation and handwritten letters. A kaleidoscopic punk rock ghost story!",
        "yt_trailer_code": "u3wPWCj2L6I",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/shirkers_2018/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/shirkers_2018/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/shirkers_2018/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/shirkers_2018/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/shirkers_2018/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/C8221D34D7454F6468DB521A63B0305988E6C2E6",
            "hash": "C8221D34D7454F6468DB521A63B0305988E6C2E6",
            "quality": "720p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "895.88 MB",
            "size_bytes": 939398267,
            "date_uploaded": "2023-12-27 09:06:10",
            "date_uploaded_unix": 1703664370
          },
          {
            "url": "https://yts.mx/torrent/download/831970EE4D1690D1AB257BA51CA3AB79AB5A0DDA",
            "hash": "831970EE4D1690D1AB257BA51CA3AB79AB5A0DDA",
            "quality": "1080p",
            "type": "web",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "5.1",
            "seeds": 67,
            "peers": 25,
            "size": "1.79 GB",
            "size_bytes": 1921997865,
            "date_uploaded": "2023-12-27 10:28:20",
            "date_uploaded_unix": 1703669300
          }
        ],
        "date_uploaded": "2023-12-27 09:06:10",
        "date_uploaded_unix": 1703664370
      },
      {
        "id": 58777,
        "url": "https://yts.mx/movies/the-flying-deuces-1939",
        "imdb_code": "tt0031322",
        "title": "The Flying Deuces",
        "title_english": "The Flying Deuces",
        "title_long": "The Flying Deuces (1939)",
        "slug": "the-flying-deuces-1939",
        "year": 1939,
        "rating": 6.7,
        "runtime": 69,
        "genres": ["Comedy", "Family", "War"],
        "summary":
            "Oliver is heartbroken when he finds that Georgette, the inkeeper's daughter he's fallen in love with, is already married to dashing Foreign Legion officer Francois. To forget her, he joins the Legion, taking Stanley with him. Their bumbling eventually gets them charged with desertion and sentenced to a firing squad. They manage to escape in a stolen airplane, but crash after a wild ride.—Paul Penna",
        "description_full":
            "Oliver is heartbroken when he finds that Georgette, the inkeeper's daughter he's fallen in love with, is already married to dashing Foreign Legion officer Francois. To forget her, he joins the Legion, taking Stanley with him. Their bumbling eventually gets them charged with desertion and sentenced to a firing squad. They manage to escape in a stolen airplane, but crash after a wild ride.—Paul Penna",
        "synopsis":
            "Oliver is heartbroken when he finds that Georgette, the inkeeper's daughter he's fallen in love with, is already married to dashing Foreign Legion officer Francois. To forget her, he joins the Legion, taking Stanley with him. Their bumbling eventually gets them charged with desertion and sentenced to a firing squad. They manage to escape in a stolen airplane, but crash after a wild ride.—Paul Penna",
        "yt_trailer_code": "cEpuQyaano8",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/the_flying_deuces_1939/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/the_flying_deuces_1939/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/the_flying_deuces_1939/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/the_flying_deuces_1939/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/the_flying_deuces_1939/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/78F8C644482A7A7A9E1DDC6F2C44F98392A23029",
            "hash": "78F8C644482A7A7A9E1DDC6F2C44F98392A23029",
            "quality": "720p",
            "type": "bluray",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "628.81 MB",
            "size_bytes": 659355075,
            "date_uploaded": "2023-12-27 18:11:44",
            "date_uploaded_unix": 1703697104
          },
          {
            "url": "https://yts.mx/torrent/download/A0B893DBA0B149B2D23D5AC9C79525B4B796931A",
            "hash": "A0B893DBA0B149B2D23D5AC9C79525B4B796931A",
            "quality": "1080p",
            "type": "bluray",
            "is_repack": "0",
            "video_codec": "x264",
            "bit_depth": "8",
            "audio_channels": "2.0",
            "seeds": 0,
            "peers": 0,
            "size": "1.14 GB",
            "size_bytes": 1224065679,
            "date_uploaded": "2023-12-27 20:01:47",
            "date_uploaded_unix": 1703703707
          }
        ],
        "date_uploaded": "2023-12-27 18:11:44",
        "date_uploaded_unix": 1703697104
      }
    ]
  },
  "@meta": {"server_time": 1703753038, "server_timezone": "CET", "api_version": 2, "execution_time": "0 ms"}
};
final Map<String, dynamic> data = json['data']! as Map<String, dynamic>;
final List<Map<String, dynamic>> movies = data['movies'];

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.blue,
        title: const Text('Movie Api Showcase'),
        centerTitle: true,
      ),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: ListView.builder(
          itemCount: movies.length,
          itemBuilder: (BuildContext context, int index) {
            final Map<String, dynamic> movie = movies[index];
            final String title = movie['title'].toString();
            final String imageUrl = movie['large_cover_image'].toString();
            return ListTile(
              title: Text(title),
              leading: GestureDetector(
                onTap: () {
                  showDialog(
                    context: context,
                    builder: (BuildContext context) {
                      return Dialog(
                        child: SizedBox(
                          width: MediaQuery.of(context).size.width * 0.8,
                          height: MediaQuery.of(context).size.height * 0.6,
                          child: Image.network(
                            imageUrl,
                            fit: BoxFit.cover,
                          ),
                        ),
                      );
                    },
                  );
                },
                child: Image.network(
                  imageUrl,
                  width: 50,
                  height: 50,
                  fit: BoxFit.cover,
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}
